### ISSUE TITLE
Running docker-maven-plugin as DOOD

### ISSUE THREAD

**Issue by kucera-jan-cz** [fabric8io/docker-maven-plugin#1005]
### Description
Hello everyone, before describing my problem, please note that I am a newbie in Docker world.
I am trying to setup build pipeline for our project on Jenkins. The Jenkins itself is setup already as docker container running as DooD. Currently the jenkins job which is suppose to build our docker images is running under non-root account (but being in docker group) but whenever I ran the job, maven plugin fails with following error:
### Error
```
No <dockerHost> given, no DOCKER_HOST environment variable, no read/writable '/var/run/docker.sock' or '//./pipe/docker_engine' and no external provider like Docker machine configured -> [Help 1]
```
After digging for the issue I ran into a note that **docker-maven-plugin** will not be working in DooD setup. Is this assumption correct?

Thanks in advance for your answer

P.S: Sorry for my English, it's a bit rusty

**Comment by rhuss** [comment]
What do you mean with DooD ? Docker in Docker ?

Actually, I think the error message is quite expressive, but happy to improve this.

**Comment by rhuss** [comment]
Yes, this should (and is known to be perfectly working). The error message means, that your original bind mount didn't work, so that's the main reason. You have to investigate your Jenkins setup, and check whether the container in which you start maven really has access to the Docker socket. You could try to run a dummy container with a 'wait', exec into it and check for the existing of the socket.

#864 is about additional volume mounts for your build so not so much relevant here.

That's probably the best I can help here for you, so I'm closing the issue. Feel free to reopen it, if you still feel this is an issue with with this plugin.
