### ISSUE TITLE
Unable to build with http registry 

### ISSUE THREAD

**Issue by SirWayne** [fabric8io/docker-maven-plugin#1077]
With our private registry that only allows http access I can not build the container with the fabric8 maven plugin. The error message is:

```
[INFO] --- docker-maven-plugin:0.26.1:push (docker-push-image) @ myservice ---
[INFO] DOCKER> The push refers to repository [xxx:8081/myadmin/myservice]
[ERROR] DOCKER> Unable to push 'myadmin/myservice:latest' from registry 'rb-repobci.de.bosch.com:8081/repository/docker-hosted' : Get https://xxx:8081/v2/: http: server gave HTTP response to HTTPS client  [Get https://xxx:8081/v2/: http: server gave HTTP response to HTTPS client ]
```

*d-m-p version : 0.26.1
*Maven version : 3.3.0

Is there a way how i can set http as protocol or a property like `allowInsecureRegistries `?

**Comment by rhuss** [comment]
A push happens always via the connected Docker daemon, never directly. In order to convince the Docker daemon to push via http to a certain registry you have to confiure the Docker daemon with `--insecure-registry` to point to your regisry (host:port). 

The plugin has no way to indicate which protocol (http/https) to use.


You will experience the same issue when you use the Docker CLI to push the image.

As this is very likely not a d-m-p issue, I'm closing this one. But feel free to reopen it if this is not the case.

**Comment by SirWayne** [comment]
Thanks for the quick response.
