### ISSUE TITLE
[feature] add imagePullPolicy: IfNotBuilt

### ISSUE THREAD

**Issue by jakub-bochenski** [fabric8io/docker-maven-plugin#1096]
We would like to make sure that we are using latest version of base images.

`imagePullPolicy: Always` is useful for this if you are only doing start/stop or only build.

For images that you build and then run the behavior is counter-productive. 
E.g. we build and run an image for running tests that is not available in any remote. In this case the start goal will fail trying to pull the image.

A workaround is to split build and start goals configuration to only set `imagePullPolicy: Always` for build and not for start. 

I wonder how complicated it would be to keep a list of images built during the run. I expect it would be something similar to the list of managed containers to be stopped?

* d-m-p version : 2.7.1

**Comment by brenuart** [comment]
+1 on this one.
Ideally, the plugin should not try to pull the image being built from the registry.

One would say you can always use `docker.imagePullPolicy.build=always` and `docker.imagePullPolicy.run=IfNotPresent` (cfr. http://dmp.fabric8.io/#property-configuration).

Although you now have the guarantee to be up-to-date when building the image, you may still run with obsolete images during your integration tests :(

I found these two properties in the plugin documentation at http://dmp.fabric8.io but could not make them work properly... After a (very) quick look at the code, I have the feeling they are not supported

**Comment by rhuss** [comment]
Actually you can specify the pullPolicy on various levels (and this is [supported](https://github.com/fabric8io/docker-maven-plugin/blob/edaad99579c6e92d697a990c4e3cc288189c42ee/src/main/java/io/fabric8/maven/docker/BuildMojo.java#L85-L87) indeed):

* On the global level which is used as a fallback if not given in any `<build>` or `<run>` configuration
* On the `<build>` level for building images
* On the `<run>` level when running containers.

If you use properties then the properties `docker.imagePullPolicy.build` and `docker.imagePullPolicy.run` are evaluated, respectively (no fallback here).

I agree completely with your use case, but I think that your use case can be supported by:

* A policy of `Always` for building
* A  policy of `IfNotPresent` for running
* Ensure that a build will always be performed before a build. This can be achieved by the proper execution bindings (e.g. to `mvn install`) and using standard Maven lifecycle phase goals when doing a CI

Tbh, I hesitate a bit to make this mode more complex, because it's super hard and fragile to make one goal to know whether another has been run before (e.g. for `run` whether `build` has been run). This also breaks the assumption that `mvn docker:build; mvn docker:run` is equivalent to `mvn docker:build docker:run`. I really had some time previously to resolve this kind of situations, and prefer to keep all goals self-contained and independent.

However, I'm of course open for a better solution. But I think an `IfNotBuilt` won't cut it because of so many things which can go wrong here.

**Comment by jakub-bochenski** [comment]
> I hesitate a bit to make this mode more complex, because it's super hard and fragile to make one goal to know whether another has been run before (e.g. for run whether build has been run). This also breaks the assumption that mvn docker:build; mvn docker:run is equivalent to mvn docker:build docker:run. I really had some bad time previously to resolve this kind of situations, and prefer to keep all goals self-contained and independent.

I agree, apparently I didn't think this request through. 
I would rather use the `run/build` slit than deal with problems caused by ignoring the constraints maven imposes on the plugins.
