### ISSUE TITLE
Do not tag every image with latest

### ISSUE THREAD

**Issue by bennypi** [fabric8io/docker-maven-plugin#1270]
### Description
Currently, every image that is built with d-m-p is automatically tagged with <image_name>:latest. When adding a <tags> section to the <build> section in the pom.xml, the newly built image is additionally tagged with the given tags, but it will still be tagged with latest.

My problem is, when running docker:build and docker:push, both latest and the additional tags will be pushed to the registry. In my case I do not want the latest tag to be pushed, only the additional tags. 

I already looked at the source code, unfortunately the tagging with latest is, as far as I can tell, happening in UrlBuilder#buildImage() where a "t" parameter is added to the build command. Therefore it is not possible to disable the tagging with latest without modifying the code of d-m-p.

### Info

* d-m-p version : 0.31.0
* Maven version (`mvn -v`) : 3.5.4
* Docker version : Docker version 19.03.1, build 74b1e89e8a

**Comment by rhuss** [comment]
> Currently, every image that is built with d-m-p is automatically tagged with <image_name>:latest. When adding a section to the section in the pom.xml, the newly built image is additionally tagged with the given tags, but it will still be tagged with latest.

No, an image is not unconditionally tagged always with `latest`, you can (and should) specify a tag as part of the image `<name>` and only use `<tags>` for _additional_ tags. 

How does you configuration look like ?

**Comment by bennypi** [comment]
I did not add the tag to the <name> section. Now with the tag in the name, the image is no longer tagged with latest.
Thank you very much for your help.

**Comment by DimitriosSG** [comment]
The way the plugin operates when no tag is provided in the image name is still pretty terrible because it adds the latest tag to builds that nobody asked it to. If for example you are building multiple git branches of a maven project, and your workflow involves tagging the master branch (and only the master branch) with latest (by passing  -Ddocker.tags.idx=latest only to the build for the master branch), you suddenly have all kinds of non-master builds tagged as "latest".

Many places use "latest" as a substitute for " latest build on master".

**Comment by rohanKanojia** [comment]
@DimitriosSG : As far as I remember only `-SNAPSHOT` builds are tagged with latest. Is it not correct?

**Comment by Postremus** [comment]
@DimitriosSG @rohanKanojia 
This is the same use case I had in mind with #1495. I even provided a few PRs to change this behaviour, which in the end we had to revert.

There is a simple solution is simple, but not really documented (afaik).

When specifying the image name as `name>${docker.name}</name>`, latest is assumed.
You can change this behaviour though, by specifying the default tag like `name>${docker.name}:${project.version}</name>`. This is what we are using in our projects right now, and works without a flaw.

**Comment by DimitriosSG** [comment]
@Postremus 

The problem is that the company I work for has hundreds of repos with pom.xml files, some specifying a tag in the name and some not (we switched to the "best practice" of specifying a tag in the name midway through), so now we have to check every one of our repos and change when needed.

Essentially, the plugin behaviour changed substantially between minor versions and there is no way to mitigate it.

**Comment by rhuss** [comment]
> The way the plugin operates when no tag is provided in the image `<name>` is still unsatisfactory, because it adds the "latest" tag to builds that nobody asked it to.

That is just not true, it is a standard Docker behaviour that when you don't specify a tag as part of a name then `latest` is assumed and automatically selected. d-m-p does nothing special here. This was the behaviour of Docker since it beginnings:

```
# Creater Image "test" without tag
$ docker build -t test .
# Check for the image that has been created:
$ docker images
REPOSITORY     TAG       IMAGE ID       CREATED          SIZE
test           latest    a059ef8a729f   27 seconds ago   38.7MB
``` 

It was a Docker design decision to make the tag part of the name. I'm not happy with that, but d-m-p respects this decision, so when you use a name without a tag, the *Docker* daemon assumes `latest`. Nothing d-m-p can prevent here.

> Essentially, the plugin behaviour changed substantially between minor versions and there is no way to mitigate it other than changing everything.

Can you tell me between which minor versions the behavior has been changed ? I can't see any change in the original behaviour of `<name>` at all ....

**Comment by DimitriosSG** [comment]
> That is just not true, it is a standard Docker behaviour that when you don't specify a tag as part of a name then `latest` is assumed and automatically selected. d-m-p does nothing special here. This was the behaviour of Docker since it beginnings:

Do know how I can remove the "latest" tag after docker:build but before docker:push? (we run maven in batch mode). I tried to just `docker rmi` the latest tag, but then docker:push complains

**Comment by DimitriosSG** [comment]
> That is just not true, it is a standard Docker behaviour that when you don't specify a tag as part of a name then `latest` is assumed and automatically selected. d-m-p does nothing special here. This was the behaviour of Docker since it beginnings:

Also, we _do_ provide tags to d-m-p in the pom.xml using <tags>, just not in the image <name>. This is a case of the d-m-p failing to feed this tag to Docker properly, instead it passes only the image <name> without a tag (which means Docker tags the image as "latest") and then attaching the tags in <tags> as extra. I mean, if no tag is provided in the name, wouldn't passing the first tag in <tags> make much more sense?
