### ISSUE TITLE
Integration tests not running with docker-follow

### ISSUE THREAD

**Issue by majonga88** [fabric8io/docker-maven-plugin#1278]
### Description

Hello,

When the process is killed (ctrl+c), I read the docs and I have the ability to use  `-Ddocker-follow ` to stop/remove container safely. It works well when I test it.

But, I encounter an issue when i DONT kill the process and let the process execute integration tests.

The shared project : https://github.com/majonga88/integration-tests

These command execute integration tests :
`mvn clean install` or `mvn verify`

These command NOT execute integration tests
`mvn clean install -Ddocker-follow` or `mvn verify -Ddocker-follow`

What did I miss ?

Feel free to ask, if you want more details.

Big thanks for your help.

### Info

* d-m-p version : 0.31.0
* Maven version (`mvn -v`) : 3.6.1

**Comment by rhuss** [comment]
You can't use `docker.follow` as part of integration testing, as the Maven run will block at the docker start stage and never continue (intentionally). It's only meant to use for a direct call to `docker:start`.

What is your use case ?

**Comment by majonga88** [comment]
My use is  : When i execute the integration-tests, and i kill the process with ctrl+c, it must stop and remove the current container.

**Comment by rhuss** [comment]
I see. However, I'm not sure how to implement this as the `integration-test` phase needs to call out to the `docker:stop` call when it receives a SIGINT. So this needs to be a Maven feature of `integration-test` but I'm afraid that there is nothing which allows you to catch a signal. 

'happy to help integrating a PR which add such a feature, but otherwise I haven't any time to explore this further. At the moment, dmp works as expected I would say.

Sorry ...

**Comment by majonga88** [comment]
Ok thank you, i will see how i can handle it, and if i found something, i give you an update.

**Comment by rhuss** [comment]
cool, thanks !

'hope you don't mind when I close that issue, feel free to reopen if needed.
