### ISSUE TITLE
Question about configuration to start multiple image containers (replicas) with docker maven plugin

### ISSUE THREAD

**Issue by pantinor** [fabric8io/docker-maven-plugin#1454]
Is it possible to configure the image run settings to  start multiple copies of the container image?

**Comment by rohanKanojia** [comment]
Hello, I'm not sure if it's supported. Could you please double check in our runconfiguration: http://dmp.fabric8.io/#running-containers . Maybe It might be possible if you use [docker-compose manifest  with plugin](http://dmp.fabric8.io/#docker-compose) but I'm not sure about this since I haven't used it myself.

**Comment by rohanKanojia** [comment]
@pantinor : Were you able to resolve this?

**Comment by pantinor** [comment]
Yes I simply used the image tag multiple times within the same docker plugin using different alias like "test-container-1", "test-container-2", "test-container-3".  This is good enough for our purposes in the docker plugin test environment without needing k8s and statefulset replicas.
