### ISSUE TITLE
Windows volume bind fails with `invalid volume specification`

### ISSUE THREAD

**Issue by car-roll** [fabric8io/docker-maven-plugin#1466]
### Description
When running an docker image, the following error appears:
` DOCKER> I/O Error [Unable to create container for [test-generator:1.0-SNAPSHOT] : {"message":"invalid volume specification: 'src:\\work'"} (Internal Server Error: 500)]`

Here is my configuration below. You can see I've tried a few variations to no avail. I'm not sure if it's related to the docker compose issue with setting `COMPOSE_CONVERT_WINDOWS_PATHS`, but I've tried that as well.

>             <configuration>
>                     <images>
>                         <image>
>                             <alias>test-generatorr</alias>
>                             <name>my/test-generator:${project.version}</name>
>                             <run>
>                                 <volumes>
>                                     <bind>
>                                         
>                                         
>                                         
>                                         <volume>C:\Users\sr\codebase:C:\work</volume>
>                                     </bind>
>                                 </volumes>
>                                 <log>
>                                     <date>default</date>
>                                 </log>
>                                 <wait>
>                                     <log>work complete.</log>
>                                     <time>300000</time>
>                                 </wait>
>                             </run>
>                         </image>
>                     </images>
>                 </configuration>
> 

### Info

* docker-maven-plugin version : 0.35.0
* Maven version (`mvn -v`) : 3.8.1
* Docker version : 20.10.5

**Comment by anderssakoul** [comment]
Likewise, when trying to do a Windows volume bind on a Windows Container on the latest dmp version, I see the same error.
For c:/ltc:c:/latc :
` {"message":"invalid volume specification: '/c/ltc:c:/latc'"} (Internal Server Error: 500)`
For c:\ltc\ll:c:\latc\ll : 
` {"message":"invalid volume specification: '/c/ltc/ll:c:/latc/ll'"} (Internal Server Error: 500)`
I can't find any variation of slash, backslash, colon, that will allow me to bind a local folder to a folder on my container. But I have no problem with a volume bind with docker-compose using either the old or the new syntax.

- Why was this issue closed? Was it fixed for relative paths, but not for absolute ones?
- Is the problem because of a Docker API change?
- Is there any form of spec that will work on Windows for absolute paths?

**Info**

- docker-maven-plugin version : 0.40.2, and also 0.30.0 but with different volume spec string in the error
- Maven version : 3.6.3
- Docker version : 20.10.18 API 1.41, and also with old API 1.30 but with different volume spec string in the error
- Java version : 11.0.16
- OS : Windows 10, Windows Server 2019
