### ISSUE TITLE
Cannot build docker image for a non-native platform only

### ISSUE THREAD

**Issue by peschee** [fabric8io/docker-maven-plugin#1623]
### Description

I am unable to build a docker image using buildx for **one platform** only which is not the native platform of my docker runtime.
I am running docker on a M1 Mac (`arm64`) and would like to build a `amd64` image only.

### Info

* docker-maven-plugin version : `0.40.3`
* Maven version (`mvn -v`) :
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/homebrew/Cellar/maven/3.8.6/libexec
Java version: 11.0.13, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/_custom/zulu11.52.13-ca-jdk11.0.13-macosx_aarch64/zulu-11.jdk/Contents/Home
Default locale: en_CH, platform encoding: UTF-8
OS name: "mac os x", version: "13.0.1", arch: "aarch64", family: "mac"
```
* Docker version : `Docker version 20.10.21, build baeda1f`
* Sample project : *https://github.com/peschee/fabric8-docker-image-buildx-test.git*

You can reproduce this in the sample project by running `$ mvn clean install -Pbuildx` which uses buildx as the builder.

**Comment by chonton** [comment]
The <images><image> sections do not merge.  You will need to specify <buildx> section on line 33 of your pom.xml

**Comment by peschee** [comment]
@chonton Thanks. If I want to have this activated as it is in the `pom.xml` behind a profile only, that means I have to redefine the `<images><image>…` configuration in the profile at the bottom?

That is weird. We normally use `pom.xml` very similar to the one in the example project and only trigger buildx builds with a profile, without having to re-define for example the image name `<images><image><name>`. This would indicate that the `<images><image>` section DO merge?!

**Comment by chonton** [comment]
Reviewing how maven merges inherited configuration would be useful.  See [default configuration inheritance](https://maven.apache.org/pom.html#plugins). Merging per-plugin and per-execution configuration is handled similarly.  Likewise, profile configuration also is merged. The default behavior is to merge the content of the configuration element according to element name. Usually, maven does the expected behavior.  Since &lt;images> is a collection, &lt;image> sections will be appended in &lt;images>. You can use help:effective-profile to see the behavior of maven.

Maven has no idea how to merge two &lt;image> sections. There is no directive to tell maven what the identity element is.

How you probably want to handle this is through properties. In your top level properties, set a default value:
```xml
<properties>
  <docker.platforms></docker.platforms>
</properties>
```
 In your image configuration, use the following;
```xml
<configuration>
  <images>
    <image>
      <name>${project.groupId}.${project.artifactId}</name>
      <build>
        <buildx>
          <platforms>
            <platform>${docker.platforms}</platform>
          </platforms>
        </buildx>
        <!-- add other configuration ... -->
      </build>
    </image>
  </images>
</configuration>
```
Then, add the following profile:
```xml
<profiles>
  <profile>
    <id>buildx</id>
    <properties>
      <docker.platforms>linux/amd64,linux/arm64</docker.platforms>
    </properties>
  </profile>
</profiles>
```

There is logic in docker-maven-plugin to comma split the &lt;platform> element and to ignore the &lt;buldx> section if &lt;platform> is empty.

This technique also allows you to specify the platforms on the command line using `-Ddocker.platforms=linux/arm64`

**Comment by peschee** [comment]
Thanks for all the detailed pointers @chonton I'll have a go at the proposed way. However, using this method:

```
<configuration>
  <images>
    <image>
      <name>${project.groupId}.${project.artifactId}</name>
      <build>
        <buildx>
          <platforms>
            <platform>${docker.platforms}</platform>
          </platforms>
        </buildx>
        <!-- add other configuration ... -->
      </build>
    </image>
  </images>
</configuration>
```

I probably won't be able to switch between building the image WITH and WITHOUT `buildx`. Using the profile method, I was able to do just that—enable building multi-arch using buildx only when the profile is active, otherwise build with the usual `docker build` command. I will have to see if I can come up with something else to cover this.

**Comment by peschee** [comment]
@chonton Ok, I see the issue. I was maybe a bit unclear in my initial description.

I have recreated your proposed configuration, except for the profile, which I dropped entirely. This is in a separate branch: https://github.com/peschee/fabric8-docker-image-buildx-test/tree/feature/properties-config

The issue I'm running into: I am on an `arm64` (Apple Silicon) and only want to build a `amd64` image. I'm running it with the following command in that branch: `mvn clean install -Ddocker.platforms=linux/amd64` The image is not built, and I see this message:

```
[INFO] DOCKER> Native platform not specified, no image built
```

If you're on `amd64`, you could try this yourself by running `mvn clean install -Ddocker.platforms=linux/arm64`. 

I hope this makes it a bit clearer.

**Comment by chonton** [comment]
This is the expected behavior as stated in [Section 5.1.6](https://dmp.fabric8.io/#build-buildx). This behavior is to prevent non-native images from tainting the  local image cache. 

The local image cache can not hold multi-architecture images nor can it have two platform specific images of the same name. 

What I recommend is specifying both platforms in the build phase. This will allow you to test the build and use the local image during integration testing. Then, during install or deploy phase, specify either both platforms or the amd platform for the push goal.  Any downstream consumers will be able to use the multi-architecture image.  BTW, the deploy to the registry should probably only happen from your build machine.

**Comment by peschee** [comment]
Thank you for the detailed explanation! 👍
