### ISSUE TITLE
Which minimal Maven version is usable?

### ISSUE THREAD

**Issue by vberruchon** [fabric8io/docker-maven-plugin#290]
Sorry if it's more a question than an issue but I'd like to know if the defined prerequisite on the maven version  >=3.2.1 is a strong dependencies or if it could be possible to use an older one?
https://github.com/vberruchon/docker-maven-plugin/commit/3b63fce296a91d4e641667a310809f9105b465e5

I'm working on a CI platform using Maven 3.0.3 and it will be hard to change for the moment :( 

I've quickly cloned the m-d-p and changed this prerequisite to 3.0.3 and test it in my project to build and start an image and it seems to work... 
So is there some reason to impose this version, and what would be the risk to use an older one like the 3.0.3?

Thank you

**Comment by rhuss** [comment]
I'll have to check, I know there is some stuff which only works on newer Maven version.

**Comment by vberruchon** [comment]
I did mention that it seems to work using maven 3.0.3 before but it didn't. I would have to check again but I could probably build the plugin but had errors using it to build and image : 
<code>
build failed: Unable to load the mojo 'build' (or one of its required components) from the plugin 'org.jolokia:docker-maven-plugin:0.13.5-MY-SNAPSHOT': com.google.inject.ProvisionException: Guice provision errors:...
</code>
I probably could test again for more details but that's all I had kept in my notes as since that I created an another brand new plugin for our very specific needs. 
But I'm still interested by this one for the future and some others more generic needs.

**Comment by andyshinn** [comment]
I'd love to know more about this as well. We standardize on Ubuntu LTS (currently 14.04) which comes with Maven 3.0.5 and is difficult to upgrade. It would be nice to know what features specifically are required for later Maven versions and a way that we could override this requirement to use an older Maven without those features.

**Comment by kevinconaway** [comment]
@rhuss any updates here?  

As of now, Travis CI uses Maven 3.1.1 on its Trusty environment which is where Docker is supported.  This makes it hard to use this plugin as part of travis builds.

**Comment by rhuss** [comment]
Ok, I will try to find out why I bumped up the version (there was a reason, I just don't remember it ;-)

**Comment by rhuss** [comment]
The issue is that the wiring of various components has changed between 3.1.x and 3.2.x so currently I ran into the same problems as [here](https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/203). 

I will try to find a solution, but for the moment 3.2.1 is the smallest working version. sorry for the moment.

**Comment by kevinconaway** [comment]
Isn't that a _build_ time dependency though?  Is the dependency necessary for the actual runtime of the plugin?

If you compile against maven 3.2.x, will the plugin still run with maven 3.1 or 3.0?

**Comment by rhuss** [comment]
Unfortunately its a runtime requirement. I can build it with 3.0.5 libs with only minor glitches (which I could resolve), but using it fails on 3.0.x and 3.1.x when wiring the internal container where I use some own [components](https://github.com/rhuss/docker-maven-plugin/blob/master/src/main/resources/META-INF/plexus/components.xml) with dependencies on Maven provided objects. 

I'm still looking how to resolve this but it's quite tricky because of the difference between non-container objects and container objects (see e.g. [here](https://mail-archives.apache.org/mod_mbox/maven-users/201001.mbox/%3C7459404c1001021751r47761196rbdddc3bf04533e94@mail.gmail.com%3E) or [here](http://maven.40175.n5.nabble.com/Mojo-Java-1-5-Component-MavenProject-returns-null-vs-JavaDoc-parameter-expression-quot-project-quot-s-td5733805.html))

**Comment by rhuss** [comment]
I was able to adapt the Plugin for 3.0.5 (and 3.1.1), at least the first tests are positive (and I don't expect much more problems).

0.14.0-SNAPSHOT has just been pushed to Maven central, if you could give it try and give some feedback, this would be awesome.

**Comment by rhuss** [comment]
@vberruchon I just relaxed it to 3.0.3 as minimal version, should work now, too.

**Comment by vberruchon** [comment]
Great news.
I won't have time to test the plugin again those weeks to come but it would allow us enviage the use of your plugin for our CI system.

Danke schön Roland

**Comment by kevinconaway** [comment]
The changes looks good from my testing, thanks.

**Comment by kevinconaway** [comment]
@rhuss is it possible to release a new version with the new maven dependency changes?

**Comment by rhuss** [comment]
I'm about moving the plugin to a new place on github and will soon release a new version 0.14.0 when done. So hopefully either today or tomorrow.
