### ISSUE TITLE
docker:promote

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/docker-maven-plugin#314]
it would be great to have a docker promote or something of similar nature where we could specify a `from` and `to` docker registry in order to use d-m-p to pull images from say a staging registry, tag and push to another registry.

Similar to this action..

```
docker pull staging:5000/rawlingsj/example:v1
docker tag staging:5000/rawlingsj/example:v1 docker.io/rawlingsj/example:v1
docker push docker.io/rawlingsj/example:v1
```

**Comment by GKTheOne** [comment]
+1 - but not urgent :)

**Comment by rhuss** [comment]
In this respect it would be probably also good to add an additional registry related property in addition to `docker.registry`, so that two registries could be specified: One for **pulling** and one for **pushing**. This would be needed for e.g `mvn docker:build docker:push` where `docker:build` might pull the base image from an explicitely specified registry.


E.g. the autopull could work similar to the push: For a `FROM my/base` in the Dockerfile and `-Ddocker.pullRegistry=pullFromMe:5000` specified, d-m-p would do:

* Pull `pullFromMe:500/my/base`
* Tag `pullFromMe:500/my/base` --> `my/base`
* Docker build
* Remove tag

Of course version number would need to be taken into account, too and the pull would also only happen when not already locally existent.  Much like the tagging logic when doing pushes.

**Comment by rawlingsj** [comment]
Yeah that sounds great.

**Comment by rhuss** [comment]
`docker.pull.registry` and `docker.push.registry` have been introduced with 0.13.8 so this already works. 

I still dare a litte bit to implement a dedicated goal for merely using Maven to transfer a Docker image from one registry to another because it doesn't has to do much with *building* images or *running* containers as part of an application build.

For me it feels more natural to have another, non-build related too for this since I really doesn't use an build configuration. 

You still can simulate this by defining a more or less empty `<build>` section for an image like

```xml
<build>
   <name>myimage</name>
   <from>baseFromSomewhere</from>
</build>
```

and then use 

```
mvn package docker:build docker:push \
     -Ddocker.pull.registry=fromRegistry:5000 \
     -Ddocker.push.registry=toRegistry:5000
```

This would exactly mimic the desired behaviour.

@rawlingsj Does this makes sense to you ? If yes, I'd like to close this issue in order to keep d-m-p focussed on the building of stuff.

**Comment by rhuss** [comment]
As I said, in order to work agains feature bloat, I'd like to close this one. 
@rawlingsj please insist, if this is not ok for you and reopen the issue in case.
