### ISSUE TITLE
docker-maven-plugin re-launch other plugin

### ISSUE THREAD

**Issue by burtsevyg** [fabric8io/docker-maven-plugin#448]
Please see source pom.xml https://github.com/burtsevyg/test/blob/master/pom.xml for example

in log I see:
First time:

```
...
[INFO] --- maven-antrun-plugin:1.8:run (ls-command) @ docker-maven-plugin-test ---
[INFO] Executing tasks
...

```

Second time:

```
...
[INFO] >>> docker-maven-plugin:0.15.1:source (start) @ docker-maven-plugin-test >>>
[INFO]
...
[INFO] --- maven-antrun-plugin:1.8:run (ls-command) @ docker-maven-plugin-test ---
[INFO] Executing tasks
...
[INFO] <<< docker-maven-plugin:0.15.1:source (start) @ docker-maven-plugin-test <<<
```

**Comment by rhuss** [comment]
Yes, that's true and because of that `docker:source` forks the Maven lifecycle in order to create the artefacts (jars, copied resources) to include in the `docker.tar`

Hence it is probably not well suited to add as phase to the lifecycle where the the `package` phase is already called (hence it will run twice through the package phase, one because of the norma lifecycle and one for the callout by `docker:source`).

There is no easy solution for this if one want to guarantee that the *package* phase is called when running `mvn docker:start` directly. 

Maybe we should use the same 'trick' like the [maven-source-plugin](http://svn.apache.org/viewvc/maven/plugins/tags/maven-source-plugin-3.0.0/src/main/java/org/apache/maven/plugins/source/), e.g. having two goals `source:jar` and `source:jar-no-fork`, one for when called directly and the other when bound to an execution.

I will look into this and probably mimic this behaviour if I cant find a more elegant solution.
