### ISSUE TITLE
Make it possible to skip push of 'latest' image.

### ISSUE THREAD

**Issue by jbellmann** [fabric8io/docker-maven-plugin#449]
Our registry-implementation does not allow 'moving tags' like 'latest'. So every build with configured push will fail with the current implementation of 'docker-maven-plugin'. Introducing a boolean property 'docker.push.skipLatestTag' should do the trick.

I will provide an PR.

Thanks

**Comment by jgangemi** [comment]
this is a dup of #413...

**Comment by rhuss** [comment]
Not sure that #413 is the same, since here's it about not pushing `latest` (but any other tag). Think it might be useful, but maybe we can make it a bit more flexible, e.g. a property like `docker.push.skipTags` which, if set to true, skips all tags, if set to `latest`, skip the `latest` tag or if set to a comma separated list like `latest,SNAPSHOT` would skip all those tags. That would be similar in semantics like we have for `docker.image` to only process a subset of the configured images.

wdyt ?

**Comment by rhuss** [comment]
@jbellmann just out of curiosity. So you are allowed to push fixed tags with version, even when the already would exist in the registry or do you increase the tag before each push ?

**Comment by jgangemi** [comment]
this seems like a mis-configuration then no? if you can't push `latest` tag, then why would you let your build tag it w/ that in the first place.

but yeah, what you suggest might be a better alternative except i think we should just rely on the existing `docker.skipTags` property instead of creating something new.

**Comment by rhuss** [comment]
Sounds fine for me as long as both have the same semantics (so we might need to update `skipTags` for the build case, too).

Please see also my comment at https://github.com/jbellmann/docker-maven-plugin/commit/7925d48ef13418b1d261eca697c8f0986223178f#comments

**Comment by jbellmann** [comment]
Hi @all,
thanks for the fast response. I will try to make some things more clear.
I think, it's not a duplication of #413. When I get it right, #413 will skip pushing images completely. That's not what I want to have. I think that at least one version/tag should be mandatory, but that's not  in the PR  :-) . Our goal is to avoid 'moving tags' (like latest, you never really know what's inside). That's the reason why our developers see something like:
```
"tag latest is not allowed"
```
We also do not allow redeployments of same version again. So for every push to the registry our engineers have to increase the version/tag (e.g. with buildnumber or timestamp). In fact, we handle it as simple artefact build by any build-tool (Maven, Gradle ... ).

Regards,
Jörg

**Comment by jbellmann** [comment]
Hi,
I had a look again into the sources, especially the 'ImageName' and 'ImageNameTest' and I think the issue and the PR is not really needed. Instead of :
```
<name>${docker-image-name}</name>
<build>
	<from>${docker-image-from}</from>
	<maintainer>${docker-image-maintainer}</maintainer>
	<tags>
		<tag>${project.version}</tag>
	</tags>
```
I can use:
```
<name>${docker-image-name}:${project.version}</name>
<build>
	<from>${docker-image-from}</from>
	<maintainer>${docker-image-maintainer}</maintainer>
	<!-- 
	<tags>
	</tags>
	 -->
```
to get what I want.

If you would confirm that I will close the issue tomorrow.
Thanks for your time.

Regards,
Jörg

**Comment by rhuss** [comment]
Yes, that the canonical. The 'main' tag is provided as part of the image name, the `<tags>` are for adding *additional* tags. So if you only need a single tag, simply add it to the name and avoid `<tags>`.

**Comment by rhuss** [comment]
If you dont mind, I'll close this one (and progress about a `skipTags` option continues in #413)

**Comment by jbellmann** [comment]
Many thanks.
