### ISSUE TITLE
Support Net Aliases

### ISSUE THREAD

**Issue by Khazrak** [fabric8io/docker-maven-plugin#466]
In Docker 1.10 you can set multiple net aliases for a container to be reached (inside user created network):
https://docs.docker.com/engine/userguide/networking/configure-dns/

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container
(The last part of the creation JSON, NetworkingConfig)

**Comment by rhuss** [comment]
Yeah, that would probably make sense. Unfortunately the `NetworkingMode` is not documented, so I'm not sure whether it works only in the context of a custom network or not.

**Comment by Khazrak** [comment]
It only works in user defined network:
[https://docs.docker.com/engine/userguide/networking/work-with-networks/](https://docs.docker.com/engine/userguide/networking/work-with-networks/)

And a simple Docker test:
`docker run -d --net-alias test ubuntu:16.04 ls
e70892c0fb8af334d2d4073d992c9d2a69544a587d2b051f392679c42c3dfb11`
`docker: Error response from daemon: Network-scoped alias is supported only for containers in user defined networks.`

**Comment by danielwegener** [comment]
In fact, this is currently a blocker for me since I need bidirectional container communication by hostname (to form a hazelcast cluster). An alternative would be to use the alias naming strategy (which would start a container with the image name) - but that prevents me to run multiple "orchesters" on the same docker host at the same time (because of duplicate container names).
