### ISSUE TITLE
Trouble with Environment Variables and Assembly

### ISSUE THREAD

**Issue by joevalerio** [fabric8io/docker-maven-plugin#486]
First off, I'm new to the plugin, and to docker, but maven and I are old friends.  This plugin is exactly what I am looking for and is very intuitive to use.  I'm trying to create a container to house postgres for integration tests.  The postgres image has some env params to control admin username/pwd and if you add a script to their init dir they will run it on startup.  I attached a test project to expose the issues I am facing.  When you: mvn integration-test  two things don't appear to be happening:

1. the environment variables are not getting applied
    -  please note the error listing the databases
2. the assembly does not seem to be applied to the image.
   - change the  username to postgres and run again, and note the databases.

I added a Dockerfile when built works exactly like I'd expect the plugin to behave.  I also included the docker command I am using that shows that the env variables are applied and the DBs were created.

Thanks in advance,

- Joe

```
maven: 3.3.9
jdk: 1.8.0_91
Docker:
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Wed Apr 27 15:27:26 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

[docker-plugin-tester.zip](https://github.com/fabric8io/docker-maven-plugin/files/318958/docker-plugin-tester.zip)

**Comment by rhuss** [comment]
First of all, apologies for the late answer. was away at some conferences and busy otherwise. 

To your issue: 

So the enviroment variables are applied, thats not the problem. Instead there are two problems:

* When you use an assembly it will be put by default in `/maven` within the image. You can change this directory by setting the `<basedir>` to `/` like here:

```xml
<assembly>
  <basedir>/</basedir>
  <descriptor>${basedir}/src/test/resources/docker/assemble-postgres.xml</descriptor>
</assembly>
```

* The other problem is the `<wait>` section:

```xml
<wait>
  <log>database system is ready to accept connections</log>
  <time>20000</time>
  <exec>
    <postStart>psql -U ${admin.user} -l</postStart>
  </exec>
</wait>
```
If you look closely in the output of the postgres DB you will see that the log output *database system is ready to accept connections* appears multiple times. Since the postexec comand kicks in right after the first appearance, when the DB is not ready initialised, you get this error. So, either wait only for a certain time (without checking the `<log>` line) or you better check for something unique (like 'PostgreSQL init process complete').

'hope this helps. If so, feel free to close the issue ;-)

**Comment by joevalerio** [comment]
Thanks Rowland.  I figured it was a noob issue.  Your suggestions worked perfectly.

Thanks!

**Comment by rhuss** [comment]
np, you are always welcome ;-)
