### ISSUE TITLE
current version number

### ISSUE THREAD

**Issue by jgangemi** [fabric8io/docker-maven-plugin#503]
yeah - it's been a while since i've contributed so something may have changed in this dept, but what's the deal w/ the version number being `0.15-SNAPSHOT` in `master`?

**Comment by rhuss** [comment]
glad you asked ;-)

The reason is, that I switched to a fabric8 CD pipeline, which performs deployments much faster and easiers. The main reason for using a version which doesn't depend on the patch level is that it makes merging much easier (because most conflicts happen exactly at this version numbers). Not really in the details, just remembering that I had 90% of merge conflicts exactly at the spot. Also semantically its not so bad to say 'the latest 0.15 release'.

But my @rawlingsj has some more insights on this ;-)

**Comment by jgangemi** [comment]
thanks for the explanation, makes a lot of sense. i'm all for whatever makes release processes, etc easier.

**Comment by jgangemi** [comment]
closing....

**Comment by rawlingsj** [comment]
@jgangemi yep that's right, just as @rhuss has mentioned, the aim is to reduce merge conflicts as well as prevent subsequent pull requests to update the snapshot version following a successful release.
