### ISSUE TITLE
add option so reactor builds only pull an image once

### ISSUE THREAD

**Issue by jgangemi** [fabric8io/docker-maven-plugin#504]
we have a rather large reactor build at the day job that uses the same container(s) over and over for integration testing. we have `autoPull` set to `always` to ensure we always get the latest container when the build starts but then each module in the build pulls the container over and over again which is somewhat needless and increases an already lengthy build time.

an additional option should be added (i'm open to naming) that will allow reactor projects to skip pulling images if it has been pulled by a previous module.

overloading `autoPull` w/ some additional values is also another option although i feel it could be confusing. i am happy to go w/ whatever the consensus is.

**Comment by rhuss** [comment]
What about adding an `AutoPullMode.ONCE` ? This would mean always, but only once per build (we could store a Set with fetched images in the MavenSession).

**Comment by jgangemi** [comment]
that works for me - i'll have a PR for this (and hopefully a couple other things, separate of course) in the next few days.

**Comment by rhuss** [comment]
cool ;-)

**Comment by jgangemi** [comment]
i can't find anywhere on the `MavenSession` that i can do this. the best option i have figured out thus far based on looking at the `buildnumber` is to get the list of projects in the reactor and set the image name as a property on all the projects. 

i know i have come across other plugins that try and offer `reactor` support but they are all escaping me right now, which means i can't go see what they did.

open to suggestions - i guess the other thing i could do is use a static variable.

**Comment by rhuss** [comment]
I dont recommend static variables because of possible classloader issues (afaik each module becomes its own classloader, so it depends where your class has been loaded).

What I did to share data across different pluging goal executions (in the same module, though) was to put it into the [PluginContext](https://github.com/fabric8io/docker-maven-plugin/blob/02348b1e1b596e4cd27aa21198c03470b8d54d94/src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java#L207-L214).

The same should work with `MavenSession` for global state, you could use this blueprint:

```java
Set<String> pulledImages = (Map)session.getExecutionProperties().get(SESSION_AUTO_PULLED_IMAGES);
if (pulledImages == null) {
   pulledImages = new HashSet<String>();
   session.getExecutionProperties().put(SESSION_AUTO_PULLED_IMAGES, pulledImages);
}
pulledImages.put(imageName);
```

You should use only standard types here (e.g. String) again because of classloading issues.

**Comment by jgangemi** [comment]
ah - i wasn't sure if that could be used. maven documentation is pretty crappy in this department.
