### ISSUE TITLE
why does `docker:push` push tags instead of calling `tag`?

### ISSUE THREAD

**Issue by jgangemi** [fabric8io/docker-maven-plugin#510]
while investigating a solution for #508 i noticed that we're calling `pushImage` instead of `tag` for tagging images, why is that?

**Comment by rhuss** [comment]
If you mean [this code](https://github.com/fabric8io/docker-maven-plugin/blob/2ae4aa0d18a134dcdc6006622bd9ef9b2088eaea/src/main/java/io/fabric8/maven/docker/PushMojo.java#L52-L58) then its because we are pushing the tagged images, too. The tagging happens during `docker:build`.

Or do you mean sth different ?

**Comment by jgangemi** [comment]
hrm - i guess i thought it could tag the image remotely. nothing to see here then.
