### ISSUE TITLE
Support a descriptor ref for Karaf and JBoss Fuse builds

### ISSUE THREAD

**Issue by dhirajsb** [fabric8io/docker-maven-plugin#519]
In migrating the quickstarts to new fabric8-quickstarts, I noticed that the configuration is pretty [boilerplate](https://github.com/fabric8-quickstarts/karaf-camel-log/blob/master/pom.xml#L218-L247). So the d-m-p should support a decsriptor ref, which would simplify things significantly.

**Comment by rhuss** [comment]
Maybe its better to integrate it directly into the fabric8-maven-plugin. Wherever, could you please provide the assembly descriptor for both ?

**Comment by lburgazzoli** [comment]
As suggesteb by @nicolaferraro , we may implement a custom generator for karaf, make sense ?

**Comment by rhuss** [comment]
That makes sense, too ;-) If its easy to detect that its about a Karaf build (e.g. because the karaf-maven-plugin is configured) then its really shouldn't be a problem. Currently we only have a spring-boot generator in f-m-p. But generators are really a fabric8-maven-plugin feature so we should move over there for this. 

To summarize:

* To get rid only of the [assembly descriptor](https://github.com/fabric8-quickstarts/karaf-camel-log/blob/master/pom.xml#L228-L239), we can add a `descriptorRef` to d-m-p.
* For getting rid of the whole configuration, we can create a generator in f-m-p. The generator itself can be easily customised, too, but typically makes some opinionated decisions (like the base image, the start up command etc.).

BTW, a generator needs not to be packaged with f-m-p, but can be directly picked up from the classpath. So projects could provide their own generators and include them via a plain dependency declaration. E.g. one could have an own project like 'ipaas-generators' or so, where all the boilerplate config could be put into and then referenced in the quickstarts poms as dependencies. Much like spring-starters.

**Comment by dhirajsb** [comment]
We should include the generator in the plugin in the interest of keeping the pom succinct. Also Karaf is going to be supported in f8 for the near future, so it's better to support it directly in f-m-p.

**Comment by lburgazzoli** [comment]
I'll make it next week, @rhuss  I may need some guidance ;)

**Comment by lburgazzoli** [comment]
@dhirajsb can you raise a jira and assign it to me?

**Comment by rhuss** [comment]
@lburgazzoli np, you are welcome ! you'll find me on irc, too. Over the weekend I'll polish the docs a bit so that things should be a bit clearer.
