### ISSUE TITLE
logging regression, exta newline

### ISSUE THREAD

**Issue by jgangemi** [fabric8io/docker-maven-plugin#538]
getting this output w/ `0.15.16`

```
rest-website-api> !!             -XX:+UseG1GC

rest-website-api> !!             -XX:+UseStringDeduplication

rest-website-api> !!             -XX:+HeapDumpOnOutOfMemoryError

rest-website-api> !!             -Dcom.sun.management.jmxremote.port=8585

rest-website-api> !!             -Dcom.sun.management.jmxremote.rmi.port=8585

rest-website-api> !!             -Djava.rmi.server.hostname=docker.local

rest-website-api> !!             -Dcom.sun.management.jmxremote.ssl=false

rest-website-api> !!             -Dcom.sun.management.jmxremote.authenticate=false
```

**Comment by rhuss** [comment]
Sorry, found that, too. I'm not sure whether it is really our fault, since
we haven't changed any thing here. I suspect some change in the docker api.
Whatever, I already fixed that locally, but apparently I forgot to push
before I left off to PTO. Fix is trivial, just trim a trailing newline
before printing out the logline.

Will push that next week..

Jae Gangemi <notifications@github.com> schrieb am So., 14. Aug. 2016, 18:19:

**Comment by jgangemi** [comment]
hrm - prior to that for this project i was using `0.15.11` - my co-worker has also reported there seems to be a bug in container resolution which i have been meaning to investigate but haven't had a chance to yet. hopefully this week.

either way, no worries - not the end of the world. enjoy your vacation!

**Comment by rhauch** [comment]
This extra line feed appears for me with 0.15.14, but 0.15.13 is fine with the same project build system.
