### ISSUE TITLE
Quiet mode for pull and push

### ISSUE THREAD

**Issue by hwellmann** [fabric8io/docker-maven-plugin#568]
When pushing or pulling images via `docker-maven-plugin`, the logs are cluttered with messages like

```
[INFO] DOCKER> Pulling from mytestimage

d5f03842f2c8: .
cf0970b26eb9: .
ec016687e243: .
eb1e263bea27: ....
cf0970b26eb9: ..
ec016687e243: .
```

It would be nice to have an option to suppress this output, or even to have it suppressed by default.

See https://github.com/docker/docker/issues/13588#issuecomment-242694121 for a related discussion regarding the Docker CLI.

**Comment by rhuss** [comment]
Indeed d-m-p detect whether an tty is attached and uses a progress meter only in this case. If not, it use the *simplified* dotted output that you describe. But I agree, it make sense that when no tty is added it probably would make sense to not output any progress at all (however, I always hesitate to ommit *all* progress for long running steps, even when used in an CI system in order to see *some* progress)

**Comment by rhuss** [comment]
I reduced now the amount of log output for the non-color mode drastically, so that the progressmeter should fit in a single line. 

Hope that solves the issue.

**Comment by rhuss** [comment]
Also, if -B is used now, then no progress meter is shown since 0.16.6
