### ISSUE TITLE
Support Remote Dockerfile Build Context

### ISSUE THREAD

**Issue by midnightconman** [fabric8io/docker-maven-plugin#627]
### Description
In Docker 1.12 you can now specify a dockerfile context of tarball reference, git, or a local text file (https://docs.docker.com/engine/reference/commandline/build/). Is it possible to add this functionality to the existing build functionality?

### Info

```
* Docker version : 1.12+
* If it's a feature request, what is your use case : Being able to use a dockerfile stored in github, instead of a local text file dockerfile

**Comment by midnightconman** [comment]
This issue is stale, closing.  :smile:

**Comment by rhuss** [comment]
Sorry and apologies that you never got an answer. Totally overlooked and then the issue got buried in the issue backlog grave ;-( Thanks for coming back (but I wouldn't probably had much time for implementing this anyway as I'm an integrating-contributions mode only since quite some time, because of lack of time).

Happy new year btw ! ;)
