### ISSUE TITLE
Delete from registry

### ISSUE THREAD

**Issue by msvticket** [fabric8io/docker-maven-plugin#688]
### Description

We primarily use docker with feature branches and when the feature branch is finished we want the corresponding images to be deleted from our registry. So we would like a goal like docker:registry-delete.

### References

https://docs.docker.com/registry/spec/api/#deleting-an-image
https://github.com/docker/docker-registry/issues/988#issuecomment-224280919

**Comment by rhuss** [comment]
This cannot be performed by this plugin easily.

The problem is, that d-m-p only talks with the Docker daemon, never directly with the Docker registry. And unfortunately the Docker daemon doesn't provide an API method for removing an image from a registry (it supports e.g. pulling from a registry, where the client (d-m-p) calls the Docker daemon which in turn calls the registry).

For implementing this feature one would need to add a whole can of worms like managing authentication against a registry directly, cert handling, ....

So I'm afraid this is out of scope for this plugin. However, if the [Docker API](https://docs.docker.com/engine/reference/api/docker_remote_api/) would support image removes from a registry, this feature could be considered to be included. Maybe you open an issue over there ?
