### ISSUE TITLE
Can't read user input inside the Docker

### ISSUE THREAD

**Issue by yyunikov** [fabric8io/docker-maven-plugin#708]
### Description
I'm writing a simple console application that starts in a Docker container, reads user input and processes it.
The code for reading user input is the following:
`new Scanner(System.in).nextLine()`
Tried also the following:
`new BufferedReader(new InputStreamReader(System.in)).readLine()`
Running an application without Docker works in both cases.

I run the docker with command:
`mvn clean docker:build docker:run`

However when it comes to user input it simply returns `null` and doesn't block for user input. In case of `Scanner` I get `java.util.NoSuchElementException: No line found` which is basically the same.
I've found a similar issue on [StackOverflow](http://stackoverflow.com/a/25378143/1889928) where passing the command line parameters `-i -t`seem to help. 

Is there any way I could add these command line parameters to Maven run configuration? Or any ideas why this issue happens?

### Info
* Maven version : 3.3.9
* Docker version : 1.13.1

**Comment by rhuss** [comment]
In short, not that's not possible since d-m-p doesn't use the CLI but the Rest API directly.

d-m-p is not a full replacement for the CLI. It's focused on building and running for automated tests. In order to support interactive input (that's what -i for the CLI does) the way how we access the build needs to be changed. So, while this might be a nice to have feature, its (very likely) quite difficult to implement given the current architecture and its not high in piority.

But if you feel fancy, feel free to submit a PR.

**Comment by yyunikov** [comment]
Thanks for the answer @rhuss.
