### ISSUE TITLE
Does dockerFileDir work with assemblyConfiguration?

### ISSUE THREAD

**Issue by nebnagrom** [fabric8io/docker-maven-plugin#809]
Version 0.21.0

I have a project that is currently configured using a external dockerFileDir

```
<build>
 <dockerFileDir>wibble</dockerFileDir>
```

I then wanted to copy a script 'start.sh' which was in the dockerFileDir but the copy command fails as it doesn't seem to be copying the files across.

I ended up getting something working using the jolokia assembly example. But i noticed that if you use the 'dockerFileDir' then instructions in the assembly are ignored. Is this correct?

If so I can look at updating the documentation to reflect this.

**Comment by rhuss** [comment]
From the documentation:

_Adding assemblies in Dockerfile mode_

Any additional files located in the dockerFileDir directory will also be added to the build context as well. You can also use an assembly if specified in an assembly configuration. However you need to add the files on your own in the Dockerfile with an ADD or COPY command. The files of the assembly are stored in a build context relative directory maven/ but can be changed by changing the assembly name with the option <name> in the assembly configuration.

E.g. the files can be added with

Example:
```
COPY maven/ /my/target/directory
```

so that the assembly files will end up in /my/target/directory within the container.

---------

Sorry, if this part is too hidden or maybe not so clear. Any suggestions for improvement are welcome.

**Comment by nebnagrom** [comment]
Further digging showed I had used a exclude file which is what broke it. 

Not a bug / problem
