### ISSUE TITLE
Timeframe for releasing 0.22?

### ISSUE THREAD

**Issue by chonton** [fabric8io/docker-maven-plugin#839]
### Description
When will 0.22 be available at maven central?  I need several features available in 0.21-SNAPSHOT. (Our corporate policy requires use of only released work.) 

Thanks, and do you need any help closing must have items for 0.22?

### Info
* d-m-p version : 0.21-SNAPSHOT

**Comment by rhuss** [comment]
Good point, I'm triggering a 0.22 today.

Currently there is no big plans with d-m-p (mostly because of lack of time ;-(, however in the long run I'd like to add the generator framework (for spring-boot, vertx, wildfly-swarm, ...) we are using in fabric8-maven-plugin to d-m-p (or better to [fabric8-build](https://github.com/fabric8io/fabric8-build) for the common parts)

**Comment by rhuss** [comment]
Arghh, totally forgot the release. Task overflow. When I'm back home I will do it tomorrow.

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by chonton** [comment]
No worries...

**Comment by rhuss** [comment]
Just released 0.22.0 (also with some dependency updates). 

sorry for the delay again.
