### ISSUE TITLE
RFE: Auto-Remove flag for docker:start

### ISSUE THREAD

**Issue by ascheman** [fabric8io/docker-maven-plugin#841]
When using the plugin for integration tests started Docker containers during pre-integration-test phase are not stopped if the integration-test phase fails, since the post-integration-test phase is never reached. In this case I have to stop + rm the container manually. I would like to see a flag (or even default behaviour) to make Docker destroy the container if it is stopped manually afterwards, i.e., as if it was started with `--rm` during `docker run`.

**Comment by rhuss** [comment]
Actually, that's not really a problem of d-m-p but because of the surefire-maven-plugin executing the integrations tests. As mentioned in the docs, it is recommended to use the failsafe-maven-plugin for this purpose as this call post-integration phase goals in any case.

I hope this solves your issue so I'm closing this issue, but feel free to reopen it if this is not the case.

**Comment by ascheman** [comment]
We are already using failsafe-maven-plugin. Sometimes we have to abort the integration test by killing Maven (Ctrl-C). In this case the trap handler does not stop the Docker containers started by d-m-p. Then it would be convenient to just stop them and have them automatically removed by the Docker daemon.
