### ISSUE TITLE
Use env variable at runtime for java args

### ISSUE THREAD

**Issue by cesartl** [fabric8io/docker-maven-plugin#878]
I'm doing something like this:

```xml
<entryPoint>
    <exec>
        <arg>java</arg>
        <arg>-XX:+UseG1GC</arg>
        <arg>-XX:MaxGCPauseMillis=400</arg>
    </exec>
</entryPoint>
```
For example I would like to control the GC pause time with a docker environment variable. I don't want to use a maven variable as I want to control this at runtime. I tried 

```xml
<entryPoint>
    <exec>
        <arg>java</arg>
        <arg>-XX:+UseG1GC</arg>
        <arg>-XX:MaxGCPauseMillis=$GC_PAUSE</arg>
    </exec>
</entryPoint>
```
which when ran gives `Improperly specified VM option 'MaxGCPauseMillis=$GC_PAUSE'`

then I tried:

```xml
<entryPoint>
    <exec>
        <arg>java</arg>
        <arg>-XX:+UseG1GC</arg>
        <arg>-XX:MaxGCPauseMillis=\$GC_PAUSE</arg>
    </exec>
</entryPoint>
```
which gives me an error: `Filename too long` or `File not found`

What is the canonical way for doing this?

**Comment by scoplin** [comment]
I think this is more of a docker thing.  It doesn't necessarily do environment variable interpolation when using the exec form for the ENTRYPOINT/CMD.  See this [docker issue](https://github.com/moby/moby/issues/4783).

I suspect you can get it to do what you want if you use the `<shell>` form for `entryPoint` instead.  Of course you give up distinct args and some signal handling control if you do that since you're introducing a parent shell which doesn't necessarily propagate signals.

    <entryPoint>
        <shell>java -XX:+UseG1GC -XX:MaxGCPauseMillis=$GC_PAUSE</shell>
    <entryPoint>

Alternatively, you could use a bash wrapper script for your entrypoint and explicitly handle arguments.

    <entryPoint>
        <arg>wrapper.sh</arg>
    </entryPoint>

Where `wrapper.sh` is something like:

    #!/bin/bash
    exec java -XX:+UseG1GC "-XX:MaxGCPauseMillis=$GC_PAUSE" "$@"

**Comment by cesartl** [comment]
the wrapper solution worked well for me thanks
